name: Build
run-name: Build

on:
  # build on pushes to release branches
  push:
    branches:
      - 'mps/20**'
      - 'merge/20**'
      
  # build on new PRs
  pull_request:

  # allow manual execution just in case
  workflow_dispatch:

jobs:
  assembleWholeProject:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-assembleWholeProject-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-assembleWholeProject-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-assembleWholeProject-
          gradle-
    - name: Assemble
      run: ls -lah
      
