name: Merge and PR into 2021.1
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'mps/2020.3'
jobs:
  merge-and-PR-into-2021-1:
    # only trigger if it was actually merged
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    steps:

      # checkout the target branch
      - name: Checkout mps/2021.1
        uses: actions/checkout@v3
        with:
          ref: 'mps/2021.1'
          fetch-depth: 0
            
      # actually merge from the previous branch
      - name: Perform merge from 2020.3 to 2021.1
        run: |
         git config user.name 'github-actions[bot]'
         git config user.email 'github-actions[bot]@users.noreply.github.com'
         git merge origin/mps/2020.3 --
        
      # create a PR based on the merge
      - name: Create PR for MPS 2021.1
        uses: peter-evans/create-pull-request@v5
        with:
          branch: 'autoPR/mps/2021.1'
          commit-message: Merge mps/2020.3 into mps/2021.1
          title: ${{ github.event.pull_request.title }} (2020.3 -> 2021.1)
          body: |
            This is an automatic PR which merges changes from `mps/2020.3` to `mps/2021.1`
            
            [Original PR content on `mps/2020.3`:](${{ github.event.pull_request._links.html.href }})
            
            > ${{ github.event.pull_request.body }}
