name: Publish
run-name: Publish

on:
  # release on tagging
  push:
    tags:
      - 'testprefix**'

  # allow manual execution just in case
  workflow_dispatch:

jobs:
  newRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on master branch
        if: startsWith(github.ref, 'mps/202') == false
        run: exit -1
      - uses: actions/checkout@v2 
      - name: something
        run: ls -lah && echo "done"
   
