name: tagchaos
run-name: tagchaos

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'mps/2022.2'

  # allow manual execution just in case
  workflow_dispatch:

env:
   GITHUB_TOKEN: ${{ secrets.MPS_REPO_PAT }}  

   
jobs:
  tagchaos:
  
    # only trigger if the PR was actually merged
    if: ( github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' )
    
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on MPS branch (mps/202**)
        if: ( startsWith(github.ref, 'refs/heads/mps/202') == false )
        run: echo ${{ github.event_name }} && exit -1

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MPS_REPO_PAT}}
          ref: '${{ github.ref_name }}'
          fetch-depth: 0
          persist-credentials: 'false'
          
      # actually merge from the previous branch
      - name: calculate number
        run: |
          lastVersion=$(git tag | grep "^2020.3\.[0-9]*$" | sort -V | tail -n1 | cut -d . -f 3)
          nextVersion=$((lastVersion+1))
          echo "nextVersion=$nextVersion" >> $GITHUB_ENV
          
      - name: Tag 2020.3 with new version
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.MPS_REPO_PAT }}
          CUSTOM_TAG: 2020.3.${{ env.nextVersion }}
          DEFAULT_BRANCH: mps/2020.3

      - name: Tag 2021.1 with new version
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.MPS_REPO_PAT }}
          CUSTOM_TAG: 2021.1.${{ env.nextVersion }}
          DEFAULT_BRANCH: mps/2021.1
        
      - name: Tag 2021.2 with new version
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.MPS_REPO_PAT }}
          CUSTOM_TAG: 2021.2.${{ env.nextVersion }}
          DEFAULT_BRANCH: mps/2021.2
            
      - name: Tag 2021.3 with new version
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
            GITHUB_TOKEN: ${{ secrets.MPS_REPO_PAT }}
            CUSTOM_TAG: 2021.3.${{ env.nextVersion }}
            DEFAULT_BRANCH: mps/2021.3
          
