name: Test Workflow
run-name: Test Workfloww ${{ github.event.create.ref }}

on:
  # run on tagging
  push:
    tags:
      - 'test/**'

  # allow manual execution just in case
  workflow_dispatch:

jobs:
  testWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          TAG=160 \
          for i in "2020.3" "2021.1" "2021.2" "2021.3";do \
                  echo "${i}.${TAG}"; \
                  echo "   ${i}.${TAG}"; \
                  done
      - name: Use tag as version
        run: |
          echo ${{ github.event.ref }}
          echo "${GITHUB_REF#refs/*/}"
          echo "github.event.create.ref ${{ github.event.create.ref }}"
          echo "github.event ${{ github.event }}"
          echo  GITHUB_CONTEXT 
          echo "$GITHUB_CONTEXT"
