on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'mps/2020.3'
jobs:
  createPR:
    # only trigger if it was actually merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ref: 'mps/2021.1'
          fetch-depth: 0
#      - run: |
#          echo The PR was merged ${{ github.event }} - ${{ github.event.commits[0].message }}

#      - run: |
#          git switch mps/2021.1
#          git merge mps/2020.3 --
#          git push
      - run:  echo LOL   ${{ github.event }}
      - run:  echo title  ${{ github.event.pull_request.title }}
      - run:  echo body   ${{ github.event.pull_request.body }}
      - run:  echo user   ${{ github.event.pull_request.user }}
      - run:  echo ulog   ${{ github.event.pull_request.user.login }}
      
      - run: git merge origin/mps/2020.3 --
      
      - name: Create PR for MPS 2021.1
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update authors
          title: ${{ github.event.pull_request.title }} (2020.3->2021.1)
          body: This is an automatic PR which merges changes from `mps/2020.3` to `mps/2021.1`
          branch: 'mps/2021.1/TODO'
#          branch: 'auto-pr/testing ${{ github.event.head_commit.message }}'
